#!/bin/bash
# =========================================
# 				Custom MOTD
# =========================================
#
#  Version: 0.1
#
# 	By....: Mun ~ Cameron Munroe
#	Git....: https://git.enjen.net/Munzy/custom_motd
#
# OS Code thanks to Observium!
#

clear

# =========================================
# 				Custom MOTD License
# =========================================


# The MIT License (MIT)

# Copyright (c) [2016] [Cameron Munroe ~ Mun]

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# =========================================
# 				End Custom MOTD License
# =========================================


# =========================================
# 				Observium OS Code
# =========================================


# From Code:
# URL: https://github.com/tomzx/observium/blob/svn-trunk/scripts/distro


# OS Code from Observium
# Observium License Version 1.0

# Copyright (C)2012 Adam Armstrong

# The intent of this license is to establish the freedom to use, share
# and contribute to the software regulated by this license.

# This license applies to any software containing a notice placed by
# the copyright holder saying that it may be distributed under the
# terms of this license. Such software is herein referred to as the 
# Software. This license covers modification and distribution of the 
# Software.

# Granted Rights

# 1. You are granted the non-exclusive rights set forth in this license
   # provided you agree to and comply with any and all conditions in
   # this license. Whole or partial distribution of the Software, or 
   # software items that link with the Software, in any form signifies 
   # acceptance of this license.

# 2. You may copy and distribute the Software in unmodified form 
   # provided that the entire package, including - but not restricted 
   # to - copyright, trademark notices and disclaimers, as released by 
   # the initial developer of the Software, is distributed.

# 3. You may make modifications to the Software and distribute your 
   # modifications, in a form that is separate from the Software, such 
   # as patches. The following restrictions apply to modifications:

   # a. Modifications must not alter or remove any copyright notices in 
      # the Software.
   # b. When modifications to the Software are released under this 
      # license, a non-exclusive royalty-free right is granted to the 
      # initial developer of the Software to distribute your 
      # modification in future versions of the Software provided such
      # versions remain available under these terms in addition to any 
      # other license(s) of the initial developer.

# Limitations of Liability

# In no event shall the initial developers or copyright holders be 
# liable for any damages whatsoever, including - but not restricted 
# to - lost revenue or profits or other direct, indirect, special, 
# incidental or consequential damages, even if they have been advised 
# of the possibility of such damages, except to the extent invariable 
# law, if any, provides otherwise.

# No Warranty

# The Software and this license document are provided AS IS with NO 
# WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

# =========================================
# 				End of License
# =========================================

OS=`uname -s`
REV=`uname -r`
MACH=`uname -m`

if [ "${OS}" = "SunOS" ] ; then
  OS=Solaris
  ARCH=`uname -p`
  OSSTR="${OS} ${REV}(${ARCH} `uname -v`)"
elif [ "${OS}" = "AIX" ] ; then
  OSSTR="${OS} `oslevel` (`oslevel -r`)"
elif [ "${OS}" = "Linux" ] ; then
  KERNEL=`uname -r`
  if [ -f /etc/redhat-release ] ; then
    DIST=$(cat /etc/redhat-release | awk '{print $1}')
    if [ "${DIST}" = "CentOS" ]; then
      DIST="CentOS"
    elif [ "${DIST}" = "Mandriva" ]; then
      DIST="Mandriva"
      PSEUDONAME=`cat /etc/mandriva-release | sed s/.*\(// | sed s/\)//`
      REV=`cat /etc/mandriva-release | sed s/.*release\ // | sed s/\ .*//`
    elif [ "${DIST}" = "Fedora" ]; then
      DIST="Fedora"
    else
      DIST="RedHat"
    fi

    PSEUDONAME=`cat /etc/redhat-release | sed s/.*\(// | sed s/\)//`
    REV=`cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//`
  elif [ -f /etc/SuSE-release ] ; then
    DIST=`cat /etc/SuSE-release | tr "\n" ' '| sed s/VERSION.*//`
    REV=`cat /etc/SuSE-release | tr "\n" ' ' | sed s/.*=\ //`
  elif [ -f /etc/mandrake-release ] ; then
    DIST='Mandrake'
    PSEUDONAME=`cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//`
    REV=`cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//`
  elif [ -f /etc/debian_version ] ; then
    if [ -f /etc/mailcleaner/etc/mailcleaner/version.def ] ; then
      DIST="MailCleaner"
      REV=`cat /etc/mailcleaner/etc/mailcleaner/version.def`
    else
      DIST="Debian `cat /etc/debian_version`"
      REV=""
    fi
  fi

  if [ -f /etc/UnitedLinux-release ] ; then
    DIST="${DIST}[`cat /etc/UnitedLinux-release | tr "\n" ' ' | sed s/VERSION.*//`]"
  fi

  if [ -f /etc/lsb-release ] ; then
    LSB_DIST="`cat /etc/lsb-release | grep DISTRIB_ID | cut -d "=" -f2`"
    LSB_REV="`cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d "=" -f2`"
    if [ "$LSB_DIST" != "" ] ; then
      DIST=$LSB_DIST
      REV=$LSB_REV
    fi
  fi

#  OSSTR="${OS} ${DIST} ${REV}(${PSEUDONAME} ${KERNEL} ${MACH})"
  OSSTR="${DIST} ${REV}"
elif [ "${OS}" = "Darwin" ] ; then
  if [ -f /usr/bin/sw_vers ] ; then
    OSSTR=`/usr/bin/sw_vers|grep -v Build|sed 's/^.*:.//'| tr "\n" ' '`
  fi
fi
# =========================================
# 				End Observium OS Code
# =========================================


MOTD_MYIPADDR=`wget https://www.enjen.net/ip/raw/ --inet4-only -qO- --timeout=2`
MOTD_MYIPADDR6=`wget https://www.enjen.net/ip/raw/ --inet6-only -qO- --timeout=2`
#MOTD_LASTLOGIP=`lastlog -u ${USER} | grep ${USER} | awk '{print $3}'`
#MOTD_LASTLOGTIME=`lastlog -u ${USER} | grep ${USER} | awk '{print $7,$6,$5,$9}'`
MOTD_LASTLOGIN=`last | grep -v 'still logged in' | grep 'pts' | head -3 | awk '{print "\e[92mLast Logins.:\e[39m\e[96m",$10,$7,$6,$5,$1,"=>\e[31m",$3,"\e[39m"}'`
MOTD_LOADAVG=`cat /proc/loadavg | awk '{print $1,$2,$3}'`
MOTD_UPTIME=`uptime -p`
MOTD_NETMONTH=`vnstat -m | grep \`date +"%b"\` | awk '{print $9,$10}'`
MOTD_NETMONTHS=`vnstat -m | grep \`date +"%b"\` | awk '{print $12,$13}'`
MOTD_WHO=`who --ips | sort | awk '{print "\e[92mAct. Logins.:\e[39m\e[96m",$1,"=>","\e[31m",$5,"\e[96m",$4,$3,"\e[39m"}'`
echo -e "\e[95m __    __    ___  _        __   ___   ___ ___    ___  \e[39m"
echo -e "\e[95m|  |__|  |  /  _]| |      /  ] /   \ |   |   |  /  _] \e[36m   |\_/| \e[39m"
echo -e "\e[95m|  |  |  | /  [_ | |     /  / |     || _   _ | /  [_  \e[36m   'o.o' \e[39m"
echo -e "\e[95m|  |  |  ||    _]| |___ /  /  |  O  ||  \_/  ||    _] \e[36m   =(_)= \e[39m"
echo -e "\e[95m|  '  '  ||   [_ |     /   \_ |     ||   |   ||   [_  \e[36m     U  \e[39m"
echo -e "\e[95m \      / |     ||     \     ||     ||   |   ||     | \e[39m"
echo -e "\e[95m  \_/\_/  |_____||_____|\____| \___/ |___|___||_____| \e[39m"
echo -e "\e[92mHostname....:\e[39m \e[96m`hostname -f`\e[39m"
echo -e "\e[92mOS..........:\e[39m \e[96m${OSSTR}\e[39m"
echo -e "\e[92mIPv4........:\e[39m \e[96m${MOTD_MYIPADDR}\e[39m"
echo -e "\e[92mIPv6........:\e[39m \e[96m${MOTD_MYIPADDR6}\e[39m"
echo -e "\e[92mDate........:\e[39m \e[96m`date`\e[39m"
echo -e "\e[92mLoad........:\e[39m \e[96m${MOTD_LOADAVG}\e[39m"
echo -e "\e[92mNet Use.....:\e[39m \e[96m${MOTD_NETMONTH} \e[95mused this month\e[39m"
echo -e "\e[92mNet Use /s..:\e[39m \e[96m${MOTD_NETMONTHS} \e[95mused this month\e[39m"
echo -e "\e[92mUptime......:\e[39m \e[96m${MOTD_UPTIME}\e[39m"
echo -e "${MOTD_WHO}"
echo -e "${MOTD_LASTLOGIN}"
