#!/bin/bash
# =========================================
# 		Custom MOTD
# =========================================
#
#  Version: 0.3.10
#
# 	By.....: Mun ~ Cameron Munroe
#   Github.: https://github.com/Munzy/custom_motd
#
# OS Code thanks to Observium!
#
# ASCII Art from : http://patorjk.com/software/taag/
#
# ASCII Cat From: http://www.asciiworld.com/-Cats-.html
#
clear

# Set to 0 to disabled special MOTDs. 1 to enable.
MOTD_SPECIAL_ENABLED="1"

# =========================================
# 		Custom MOTD License
# =========================================

    # Custom_MOTD : A quick computer overview in your MOTD
    # Copyright (C) {2017}  {Cameron Munroe ~ Mun }
	# munroenet@gmail.com

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.

# =========================================
# 		End Custom MOTD License
# =========================================

# =========================================
# 		Observium OS Code
# =========================================
# From Code:
# URL: https://github.com/tomzx/observium/blob/svn-trunk/scripts/distro


# OS Code from Observium
# Observium License Version 1.0
# Copyright (C)2012 Adam Armstrong
# The intent of this license is to establish the freedom to use, share
# and contribute to the software regulated by this license.
# This license applies to any software containing a notice placed by
# the copyright holder saying that it may be distributed under the
# terms of this license. Such software is herein referred to as the 
# Software. This license covers modification and distribution of the 
# Software.
# Granted Rights
# 1. You are granted the non-exclusive rights set forth in this license
   # provided you agree to and comply with any and all conditions in
   # this license. Whole or partial distribution of the Software, or 
   # software items that link with the Software, in any form signifies 
   # acceptance of this license.
# 2. You may copy and distribute the Software in unmodified form 
   # provided that the entire package, including - but not restricted 
   # to - copyright, trademark notices and disclaimers, as released by 
   # the initial developer of the Software, is distributed.
# 3. You may make modifications to the Software and distribute your 
   # modifications, in a form that is separate from the Software, such 
   # as patches. The following restrictions apply to modifications:
   # a. Modifications must not alter or remove any copyright notices in 
      # the Software.
   # b. When modifications to the Software are released under this 
      # license, a non-exclusive royalty-free right is granted to the 
      # initial developer of the Software to distribute your 
      # modification in future versions of the Software provided such
      # versions remain available under these terms in addition to any 
      # other license(s) of the initial developer.
# Limitations of Liability
# In no event shall the initial developers or copyright holders be 
# liable for any damages whatsoever, including - but not restricted 
# to - lost revenue or profits or other direct, indirect, special, 
# incidental or consequential damages, even if they have been advised 
# of the possibility of such damages, except to the extent invariable 
# law, if any, provides otherwise.
# No Warranty
# The Software and this license document are provided AS IS with NO 
# WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# =========================================
# 		End of License
# =========================================

OS=`uname -s`
REV=`uname -r`
MACH=`uname -m`

if [ "${OS}" = "SunOS" ] ; then
  OS=Solaris
  ARCH=`uname -p`
  OSSTR="${OS} ${REV}(${ARCH} `uname -v`)"
elif [ "${OS}" = "AIX" ] ; then
  OSSTR="${OS} `oslevel` (`oslevel -r`)"
elif [ "${OS}" = "Linux" ] ; then
  KERNEL=`uname -r`
  if [ -f /etc/redhat-release ] ; then
    DIST=$(cat /etc/redhat-release | awk '{print $1}')
    if [ "${DIST}" = "CentOS" ]; then
      DIST="CentOS"
    elif [ "${DIST}" = "Mandriva" ]; then
      DIST="Mandriva"
      PSEUDONAME=`cat /etc/mandriva-release | sed s/.*\(// | sed s/\)//`
      REV=`cat /etc/mandriva-release | sed s/.*release\ // | sed s/\ .*//`
    elif [ "${DIST}" = "Fedora" ]; then
      DIST="Fedora"
    else
      DIST="RedHat"
    fi

    PSEUDONAME=`cat /etc/redhat-release | sed s/.*\(// | sed s/\)//`
    REV=`cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//`
  elif [ -f /etc/SuSE-release ] ; then
    DIST=`cat /etc/SuSE-release | tr "\n" ' '| sed s/VERSION.*//`
    REV=`cat /etc/SuSE-release | tr "\n" ' ' | sed s/.*=\ //`
  elif [ -f /etc/mandrake-release ] ; then
    DIST='Mandrake'
    PSEUDONAME=`cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//`
    REV=`cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//`
  elif [ -f /etc/debian_version ] ; then
    if [ -f /etc/mailcleaner/etc/mailcleaner/version.def ] ; then
      DIST="MailCleaner"
      REV=`cat /etc/mailcleaner/etc/mailcleaner/version.def`
    else
      DIST="Debian `cat /etc/debian_version`"
      REV=""
    fi
  fi

  if [ -f /etc/UnitedLinux-release ] ; then
    DIST="${DIST}[`cat /etc/UnitedLinux-release | tr "\n" ' ' | sed s/VERSION.*//`]"
  fi

  if [ -f /etc/lsb-release ] ; then
    LSB_DIST="`cat /etc/lsb-release | grep DISTRIB_ID | cut -d "=" -f2`"
    LSB_REV="`cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d "=" -f2`"
    if [ "$LSB_DIST" != "" ] ; then
      DIST=$LSB_DIST
      REV=$LSB_REV
    fi
  fi

#  OSSTR="${OS} ${DIST} ${REV}(${PSEUDONAME} ${KERNEL} ${MACH})"
  OSSTR="${DIST} ${REV}"
elif [ "${OS}" = "Darwin" ] ; then
  if [ -f /usr/bin/sw_vers ] ; then
    OSSTR=`/usr/bin/sw_vers|grep -v Build|sed 's/^.*:.//'| tr "\n" ' '`
  fi
fi

# =========================================
# 		End Observium OS Code
# =========================================

# =========================================
# 		Getting Data
# =========================================
# getting our lovely IP (no check certificate for debian 6 and older released)
MOTD_MYIPADDR=`wget https://www.enjen.net/ip/rawz/ --inet4-only -qO- --timeout=2 --no-check-certificate | awk '{print "\\\e[96m",$1,"\\\e[95m",$2,"\\\e[39m"}'`

# getting our even cooler IP
MOTD_MYIPADDR6=`wget https://www.enjen.net/ip/rawz/ --inet6-only -qO- --timeout=2 --no-check-certificate | awk '{print "\\\e[96m",$1,"\\\e[95m",$2,"\\\e[39m"}'`

# getting our lovely IP RDNS (no check certificate for debian 6 and older released)
# MOTD_MYIPADDRR=`wget https://www.enjen.net/ip/raw/rdns/ --inet4-only -qO- --timeout=2 --no-check-certificate` 
# getting our even cooler IP RDNS
# MOTD_MYIPADDR6R=`wget https://www.enjen.net/ip/raw/rdns/ --inet6-only -qO- --timeout=2 --no-check-certificate`

# Get Kernel Info
MOTD_KERNEL=`uname -r`

# Getting Free Memory usage
MOTD_MEMFREE=`cat /proc/meminfo | grep "MemFree:" | awk '{print $2}'`

# Getting memory Cache Usages
MOTD_MEMCACHE=`cat /proc/meminfo | grep "Cached:" | awk '{print $2}'`

# Creating MOTD_MEMAVAIL Via a failback method
MOTD_MEMAVAIL=`awk "BEGIN {printf \"%.2f\",${MOTD_MEMFREE}+${MOTD_MEMCACHE}}"`

# Getting Memory Available for system
# Can't be used in older systems like Debian 6
#MOTD_MEMAVAIL=`cat /proc/meminfo | grep "MemAvailable:" | awk '{print $2}'`

# Getting Memory Total for system
MOTD_MEMTOTAL=`cat /proc/meminfo | grep "MemTotal:" | awk '{print $2}'`

#calcing the percentage used
MOTD_MEMPERC=`awk "BEGIN {printf \"%.2f\",100-${MOTD_MEMAVAIL}/${MOTD_MEMTOTAL}*100}"`

#getting last login info
MOTD_LASTLOGIN=`last -i | grep -v 'still logged in' | grep 'pts' | head -3 | awk '{print "\\\e[92mLast Logins.:\\\e[39m\\\e[96m",$10,$7,$6,$5,$1,"=>\\\e[31m",$3,"\\\e[39m"}'`

# grabbing loadavg
MOTD_LOADAVG=`cat /proc/loadavg | awk '{print $1,$2,$3}'`

# Getting Uptime the rough way.
MOTD_UPTIMESECS=`cat /proc/uptime | awk '{print $1}'`
MOTD_UPTIME=`awk "BEGIN {printf \"%.2f\",${MOTD_UPTIMESECS}/60/60/24}"`

#getting uptime (Isn't supported by older distos, might be useful in the future)
#MOTD_UPTIME=`uptime -p` 

# using vnstat for GIB used
MOTD_NETMONTH=`vnstat -m | grep \`date +"%b"\` | awk '{print $9,$10}'`

# using vnstat to gain X/s transfer
MOTD_NETMONTHS=`vnstat -m | grep \`date +"%b"\` | awk '{print $12,$13}'`

#getting who is currently logged in
MOTD_WHO=`who | sort | awk '{print "\\\e[92mAct. Logins.:\\\e[39m\\\e[96m",$1,"=>","\\\e[31m",$5,"\\\e[96m",$4,$3,"\\\e[39m"}'`

# KSM Sharing, check. 
# Built from https://github.com/tomzx/observium/blob/svn-trunk/scripts/agent-local/ksm
# -and- https://gist.githubusercontent.com/wankdanker/1206923/raw/73d864c438022ba8c92381f3eddf61bac6163b9f/ksmstat
if [ -d /sys/kernel/mm/ksm ] && [ $(cat /sys/kernel/mm/ksm/pages_shared) != "0" ] && [ "${MOTD_SPECIAL_ENABLED}" == "1" ];
then
    MOTD_KSM_SHARING=`cat /sys/kernel/mm/ksm/pages_sharing`;
    MOTD_KSM_SIZE=`getconf PAGESIZE`;
    MOTD_KSM_MEM=$(echo "scale=0;${MOTD_KSM_SHARING} * ${MOTD_KSM_SIZE}"|bc);
    MOTD_KSM_MEM=$(expr ${MOTD_KSM_MEM} / 1048576);
    MOTD_SPECIAL+="\e[92mKSM Saved...:\e[39m \e[96m${MOTD_KSM_MEM}\e[39m \e[95mMB\e[39m"
fi

# =========================================
# 		Echo the message to console. 
# =========================================

echo -e "\e[95m __    __    ___  _        __   ___   ___ ___    ___  \e[39m"
echo -e "\e[95m|  |__|  |  /  _]| |      /  ] /   \ |   |   |  /  _] \e[36m   |\_/| \e[39m"
echo -e "\e[95m|  |  |  | /  [_ | |     /  / |     || _   _ | /  [_  \e[36m   'o.o' \e[39m"
echo -e "\e[95m|  |  |  ||    _]| |___ /  /  |  O  ||  \_/  ||    _] \e[36m   =(_)= \e[39m"
echo -e "\e[95m|  '  '  ||   [_ |     /   \_ |     ||   |   ||   [_  \e[36m     U  \e[39m"
echo -e "\e[95m \      / |     ||     \     ||     ||   |   ||     | \e[39m"
echo -e "\e[95m  \_/\_/  |_____||_____|\____| \___/ |___|___||_____| \e[39m"
echo -e "\e[92mHostname....:\e[39m \e[96m`hostname`\e[39m"
echo -e "\e[92mOS..........:\e[39m \e[96m${OSSTR}\e[39m\e[31m ${MOTD_KERNEL}\e[39m"
echo -e "\e[92mIPv4........:${MOTD_MYIPADDR}"
echo -e "\e[92mIPv6........:${MOTD_MYIPADDR6}"
echo -e "\e[92mDate........:\e[39m \e[96m`date`\e[39m"
echo -e "\e[92mLoad........:\e[39m \e[96m${MOTD_LOADAVG}\e[39m"
echo -e "\e[92mMemory......:\e[39m \e[96m${MOTD_MEMPERC}\e[39m \e[95mpercent used\e[39m"
echo -e "\e[92mNet Use.....:\e[39m \e[96m${MOTD_NETMONTH}\e[39m\e[31m ${MOTD_NETMONTHS} \e[39m\e[95mused this month\e[39m"
echo -e "\e[92mUptime......:\e[39m \e[96m${MOTD_UPTIME}\e[39m \e[95mdays\e[39m"
if [ "${MOTD_SPECIAL}" != "" ] && [ "${MOTD_SPECIAL_ENABLED}" == "1" ];
then
    echo -e "${MOTD_SPECIAL}"
fi
echo -e "${MOTD_WHO}"
echo -e "${MOTD_LASTLOGIN}"
